

const data = [
    {
        stop_name: "Van Cortlandt Park - 242 St",
        stop_trains: [{ train_name: "1", train_direction: "Downtown", train_id: "101S", train_station: "Van Cortlandt Park - 242 St" }],
    },
    {
        stop_name: "238 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "103N", train_station: "238 St" }, { train_name: "1", train_direction: "Downtown", train_id: "103S", train_station: "238 St" }],
    },
    {
        stop_name: "231 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "104N", train_station: "231 St" }, { train_name: "1", train_direction: "Downtown", train_id: "104S", train_station: "231 St" }],
    },
    {
        stop_name: "Marble Hill - 225 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "106N", train_station: "Marble Hill - 225 St" }, { train_name: "1", train_direction: "Downtown", train_id: "106S", train_station: "Marble Hill - 225 St" }],
    },
    {
        stop_name: "215 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "107N", train_station: "215 St" }, { train_name: "1", train_direction: "Downtown", train_id: "107S", train_station: "215 St" }],
    },
    {
        stop_name: "207 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "108N", train_station: "207 St" }, { train_name: "1", train_direction: "Downtown", train_id: "108S", train_station: "207 St" }],
    },
    {
        stop_name: "Dyckman St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "109N", train_station: "Dyckman St" }, { train_name: "1", train_direction: "Downtown", train_id: "109S", train_station: "Dyckman St" }],
    },
    {
        stop_name: "191 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "110N", train_station: "191 St" }, { train_name: "1", train_direction: "Downtown", train_id: "110S", train_station: "191 St" }],
    },
    {
        stop_name: "181 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "111N", train_station: "181 St" }, { train_name: "1", train_direction: "Downtown", train_id: "111S", train_station: "181 St" }],
    },
    {
        stop_name: "168 St",
        stop_trains: [],
    },
    {
        stop_name: "157 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "113N", train_station: "157 St" }, { train_name: "1", train_direction: "Downtown", train_id: "113S", train_station: "157 St" }],
    },
    {
        stop_name: "145 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "114N", train_station: "145 St" }, { train_name: "1", train_direction: "Downtown", train_id: "114S", train_station: "145 St" }],
    },
    {
        stop_name: "137 St - City College",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "115N", train_station: "137 St - City College" }, { train_name: "1", train_direction: "Downtown", train_id: "115S", train_station: "137 St - City College" }],
    },
    {
        stop_name: "125 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "116N", train_station: "125 St" }, { train_name: "1", train_direction: "Downtown", train_id: "116S", train_station: "125 St" }],
    },
    {
        stop_name: "116 St - Columbia University",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "117N", train_station: "116 St - Columbia University" }, { train_name: "1", train_direction: "Downtown", train_id: "117S", train_station: "116 St - Columbia University" }],
    },
    {
        stop_name: "Cathedral Pkwy (110 St)",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "118N", train_station: "Cathedral Pkwy (110 St)" }, { train_name: "1", train_direction: "Downtown", train_id: "118S", train_station: "Cathedral Pkwy (110 St)" }],
    },
    {
        stop_name: "103 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "119N", train_station: "103 St" }, { train_name: "1", train_direction: "Downtown", train_id: "119S", train_station: "103 St" }],
    },
    {
        stop_name: "96 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "120N", train_station: "96 St" }, { train_name: "1", train_direction: "Downtown", train_id: "120S", train_station: "96 St" }, { train_name: "2", train_direction: "Uptown", train_id: "120N", train_station: "96 St" }, { train_name: "2", train_direction: "Downtown", train_id: "120S", train_station: "96 St" }, { train_name: "3", train_direction: "Uptown", train_id: "120N", train_station: "96 St" }, { train_name: "3", train_direction: "Downtown", train_id: "120S", train_station: "96 St" }],
    },
    {
        stop_name: "86 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "121N", train_station: "86 St" }, { train_name: "1", train_direction: "Downtown", train_id: "121S", train_station: "86 St" }],
    },
    {
        stop_name: "79 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "122N", train_station: "79 St" }, { train_name: "1", train_direction: "Downtown", train_id: "122S", train_station: "79 St" }],
    },
    {
        stop_name: "72 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: '123N', train_station: "72 St" }, { train_name: "1", train_direction: "Downtown", train_id: '123S', train_station: "72 St" }, { train_name: "2", train_direction: "Uptown", train_id: '123N', train_station: "72 St" }, { train_name: "2", train_direction: "Downtown", train_id: '123S', train_station: "72 St" }, { train_name: "3", train_direction: "Uptown", train_id: '123N', train_station: "72 St" }, { train_name: "3", train_direction: "Downtown", train_id: '123S', train_station: "72 St" }],
    },
    {
        stop_name: "66 St - Lincoln Center",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: '124N', train_station: "66 St - Lincoln Center" }, { train_name: "1", train_direction: "Downtown", train_id: '124S', train_station: "66 St - Lincoln Center" }, { train_name: "2", train_direction: "Uptown", train_id: '124N', train_station: "66 St - Lincoln Center" }, { train_name: "2", train_direction: "Downtown", train_id: '124S', train_station: "66 St - Lincoln Center" }, { train_name: "3", train_direction: "Uptown", train_id: '124N', train_station: "66 St - Lincoln Center" }, { train_name: "3", train_direction: "Downtown", train_id: '124S', train_station: "66 St - Lincoln Center" }],
    },
    {
        stop_name: "59 St - Columbus Circle",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "125N", train_station: "59 St - Columbus Circle" }, { train_name: "1", train_direction: "Downtown", train_id: "125S", train_station: "59 St - Columbus Circle" }, { train_name: "2", train_direction: "Uptown", train_id: "125N", train_station: "59 St - Columbus Circle" }, { train_name: "2", train_direction: "Downtown", train_id: "125S", train_station: "59 St - Columbus Circle" }, { train_name: "3", train_direction: "Uptown", train_id: "125N", train_station: "59 St - Columbus Circle" }, { train_name: "3", train_direction: "Downtown", train_id: "125S", train_station: "59 St - Columbus Circle" }],
    },
    {
        stop_name: "50 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "126N", train_station: "50 St" }, { train_name: "1", train_direction: "Downtown", train_id: "126S", train_station: "50 St" }, { train_name: "2", train_direction: "Uptown", train_id: "126N", train_station: "50 St" }, { train_name: "2", train_direction: "Downtown", train_id: "126S", train_station: "50 St" }, { train_name: "3", train_direction: "Uptown", train_id: "126N", train_station: "50 St" }, { train_name: "3", train_direction: "Downtown", train_id: "126S", train_station: "50 St" }],
    },
    {
        stop_name: "Times Square - 42 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "127N", train_station: "Times Square - 42 St" }, { train_name: "1", train_direction: "Downtown", train_id: "127S", train_station: "Times Square - 42 St" }, { train_name: "2", train_direction: "Uptown", train_id: "127N", train_station: "Times Square - 42 St" }, { train_name: "2", train_direction: "Downtown", train_id: "127S", train_station: "Times Square - 42 St" }, { train_name: "3", train_direction: "Uptown", train_id: "127N", train_station: "Times Square - 42 St" }, { train_name: "3", train_direction: "Downtown", train_id: "127S", train_station: "Times Square - 42 St" }],
    },
    {
        stop_name: "34 St - Penn Station",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "128N", train_station: "34 St - Penn Station" }, { train_name: "1", train_direction: "Downtown", train_id: "128S", train_station: "34 St - Penn Station" }, { train_name: "2", train_direction: "Uptown", train_id: "128N", train_station: "34 St - Penn Station" }, { train_name: "2", train_direction: "Downtown", train_id: "128S", train_station: "34 St - Penn Station" }, { train_name: "3", train_direction: "Uptown", train_id: "128N", train_station: "34 St - Penn Station" }, { train_name: "3", train_direction: "Downtown", train_id: "128S", train_station: "34 St - Penn Station" }],
    },
    {
        stop_name: "28 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "129N", train_station: "28 St" }, { train_name: "1", train_direction: "Downtown", train_id: "129S", train_station: "28 St" }, { train_name: "2", train_direction: "Uptown", train_id: "129N", train_station: "28 St" }, { train_name: "2", train_direction: "Downtown", train_id: "129S", train_station: "28 St" }, { train_name: "3", train_direction: "Uptown", train_id: "129N", train_station: "28 St" }, { train_name: "3", train_direction: "Downtown", train_id: "129S", train_station: "28 St" }],
    },
    {
        stop_name: "23 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "130N", train_station: "23 St" }, { train_name: "1", train_direction: "Downtown", train_id: "130S", train_station: "23 St" }, { train_name: "2", train_direction: "Uptown", train_id: "130N", train_station: "23 St" }, { train_name: "2", train_direction: "Downtown", train_id: "130S", train_station: "23 St" }, { train_name: "3", train_direction: "Uptown", train_id: "130N", train_station: "23 St" }, { train_name: "3", train_direction: "Downtown", train_id: "130S", train_station: "23 St" }],
    },
    {
        stop_name: "18 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "131N", train_station: "18 St" }, { train_name: "1", train_direction: "Downtown", train_id: "131S", train_station: "18 St" }, { train_name: "2", train_direction: "Uptown", train_id: "131N", train_station: "18 St" }, { train_name: "2", train_direction: "Downtown", train_id: "131S", train_station: "18 St" }, { train_name: "3", train_direction: "Uptown", train_id: "131N", train_station: "18 St" }, { train_name: "3", train_direction: "Downtown", train_id: "131S", train_station: "18 St" }],
    },
    {
        stop_name: "14 St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "132N", train_station: "14 St" }, { train_name: "1", train_direction: "Downtown", train_id: "132S", train_station: "14 St" }, { train_name: "2", train_direction: "Uptown", train_id: "132N", train_station: "14 St" }, { train_name: "2", train_direction: "Downtown", train_id: "132S", train_station: "14 St" }, { train_name: "3", train_direction: "Uptown", train_id: "132N", train_station: "14 St" }, { train_name: "3", train_direction: "Downtown", train_id: "132S", train_station: "14 St" }],
    },
    {
        stop_name: "Christopher St - Sheridan Sq",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "133N", train_station: "Christopher St - Sheridan Sq" }, { train_name: "1", train_direction: "Downtown", train_id: "133S", train_station: "Christopher St - Sheridan Sq" }],
    },
    {
        stop_name: "Houston St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "134N", train_station: "Houston St" }, { train_name: "1", train_direction: "Downtown", train_id: "134S", train_station: "Houston St" }],
    },
    {
        stop_name: "Canal St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "135N", train_station: "Canal St" }, { train_name: "1", train_direction: "Downtown", train_id: "135S", train_station: "Canal St" }],
    },
    {
        stop_name: "Franklin St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "136N", train_station: "Franklin St" }, { train_name: "1", train_direction: "Downtown", train_id: "136S", train_station: "Franklin St" }],
    },
    {
        stop_name: "Chambers St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "137N", train_station: "Chambers St" }, { train_name: "1", train_direction: "Downtown", train_id: "137S", train_station: "Chambers St" }, { train_name: "2", train_direction: "Uptown", train_id: "137N", train_station: "Chambers St" }, { train_name: "2", train_direction: "Downtown", train_id: "137S", train_station: "Chambers St" }, { train_name: "3", train_direction: "Uptown", train_id: "137N", train_station: "Chambers St" }, { train_name: "3", train_direction: "Downtown", train_id: "137S", train_station: "Chambers St" }],
    },
    {
        stop_name: "WTC Cortlandt",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "138N", train_station: "WTC Cortlandt" }, { train_name: "1", train_direction: "Downtown", train_id: "138S", train_station: "WTC Cortlandt" }],
    },
    {
        stop_name: "Rector St",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "139N", train_station: "Rector St" }, { train_name: "1", train_direction: "Downtown", train_id: "139S", train_station: "Rector St" }],
    },
    {
        stop_name: "South Ferry",
        stop_trains: [{ train_name: "1", train_direction: "Uptown", train_id: "140N", train_station: "South Ferry" }],
    }
]

export default data
//     {
//         "location_type": "0",
//         "parent_station": "R44",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "R44N",
//         "stop_lat": "40.622687",
//         "stop_lon": "-74.028398",
//         "stop_name": "86 St",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "R44",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "R44S",
//         "stop_lat": "40.622687",
//         "stop_lon": "-74.028398",
//         "stop_name": "86 St",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "R45",
//         "stop_lat": "40.616622",
//         "stop_lon": "-74.030876",
//         "stop_name": "Bay Ridge - 95 St",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "R45",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "R45N",
//         "stop_lat": "40.616622",
//         "stop_lon": "-74.030876",
//         "stop_name": "Bay Ridge - 95 St",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "R45",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "R45S",
//         "stop_lat": "40.616622",
//         "stop_lon": "-74.030876",
//         "stop_name": "Bay Ridge - 95 St",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S01",
//         "stop_lat": "40.680596",
//         "stop_lon": "-73.955827",
//         "stop_name": "Franklin Av",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S01",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S01N",
//         "stop_lat": "40.680596",
//         "stop_lon": "-73.955827",
//         "stop_name": "Franklin Av",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S01",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S01S",
//         "stop_lat": "40.680596",
//         "stop_lon": "-73.955827",
//         "stop_name": "Franklin Av",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S03",
//         "stop_lat": "40.674772",
//         "stop_lon": "-73.957624",
//         "stop_name": "Park Pl",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S03",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S03N",
//         "stop_lat": "40.674772",
//         "stop_lon": "-73.957624",
//         "stop_name": "Park Pl",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S03",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S03S",
//         "stop_lat": "40.674772",
//         "stop_lon": "-73.957624",
//         "stop_name": "Park Pl",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S04",
//         "stop_lat": "40.670343",
//         "stop_lon": "-73.959245",
//         "stop_name": "Botanic Garden",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S04",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S04N",
//         "stop_lat": "40.670343",
//         "stop_lon": "-73.959245",
//         "stop_name": "Botanic Garden",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S04",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S04S",
//         "stop_lat": "40.670343",
//         "stop_lon": "-73.959245",
//         "stop_name": "Botanic Garden",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S09",
//         "stop_lat": "40.512764",
//         "stop_lon": "-74.251961",
//         "stop_name": "Tottenville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S09",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S09N",
//         "stop_lat": "40.512764",
//         "stop_lon": "-74.251961",
//         "stop_name": "Tottenville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S09",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S09S",
//         "stop_lat": "40.512764",
//         "stop_lon": "-74.251961",
//         "stop_name": "Tottenville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S10",
//         "stop_lat": "40.515401",
//         "stop_lon": "-74.245689",
//         "stop_name": "Atlantic",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S10",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S10N",
//         "stop_lat": "40.515401",
//         "stop_lon": "-74.245689",
//         "stop_name": "Atlantic",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S10",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S10S",
//         "stop_lat": "40.515401",
//         "stop_lon": "-74.245689",
//         "stop_name": "Atlantic",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S11",
//         "stop_lat": "40.516578",
//         "stop_lon": "-74.242096",
//         "stop_name": "Arthur Kill",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S11",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S11N",
//         "stop_lat": "40.516578",
//         "stop_lon": "-74.242096",
//         "stop_name": "Arthur Kill",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S11",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S11S",
//         "stop_lat": "40.516578",
//         "stop_lon": "-74.242096",
//         "stop_name": "Arthur Kill",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S12",
//         "stop_lat": "40.517812",
//         "stop_lon": "-74.238373",
//         "stop_name": "Nassau",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S12",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S12N",
//         "stop_lat": "40.517812",
//         "stop_lon": "-74.238373",
//         "stop_name": "Nassau",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S12",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S12S",
//         "stop_lat": "40.517812",
//         "stop_lon": "-74.238373",
//         "stop_name": "Nassau",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S13",
//         "stop_lat": "40.519631",
//         "stop_lon": "-74.229141",
//         "stop_name": "Richmond Valley",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S13",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S13N",
//         "stop_lat": "40.519631",
//         "stop_lon": "-74.229141",
//         "stop_name": "Richmond Valley",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S13",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S13S",
//         "stop_lat": "40.519631",
//         "stop_lon": "-74.229141",
//         "stop_name": "Richmond Valley",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S14",
//         "stop_lat": "40.52241",
//         "stop_lon": "-74.217847",
//         "stop_name": "Pleasant Plains",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S14",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S14N",
//         "stop_lat": "40.52241",
//         "stop_lon": "-74.217847",
//         "stop_name": "Pleasant Plains",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S14",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S14S",
//         "stop_lat": "40.52241",
//         "stop_lon": "-74.217847",
//         "stop_name": "Pleasant Plains",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S15",
//         "stop_lat": "40.525507",
//         "stop_lon": "-74.200064",
//         "stop_name": "Prince's Bay",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S15",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S15N",
//         "stop_lat": "40.525507",
//         "stop_lon": "-74.200064",
//         "stop_name": "Prince's Bay",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S15",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S15S",
//         "stop_lat": "40.525507",
//         "stop_lon": "-74.200064",
//         "stop_name": "Prince's Bay",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S16",
//         "stop_lat": "40.533674",
//         "stop_lon": "-74.191794",
//         "stop_name": "Huguenot",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S16",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S16N",
//         "stop_lat": "40.533674",
//         "stop_lon": "-74.191794",
//         "stop_name": "Huguenot",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S16",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S16S",
//         "stop_lat": "40.533674",
//         "stop_lon": "-74.191794",
//         "stop_name": "Huguenot",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S17",
//         "stop_lat": "40.54046",
//         "stop_lon": "-74.178217",
//         "stop_name": "Annadale",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S17",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S17N",
//         "stop_lat": "40.54046",
//         "stop_lon": "-74.178217",
//         "stop_name": "Annadale",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S17",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S17S",
//         "stop_lat": "40.54046",
//         "stop_lon": "-74.178217",
//         "stop_name": "Annadale",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S18",
//         "stop_lat": "40.544601",
//         "stop_lon": "-74.16457",
//         "stop_name": "Eltingville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S18",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S18N",
//         "stop_lat": "40.544601",
//         "stop_lon": "-74.16457",
//         "stop_name": "Eltingville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S18",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S18S",
//         "stop_lat": "40.544601",
//         "stop_lon": "-74.16457",
//         "stop_name": "Eltingville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S19",
//         "stop_lat": "40.551231",
//         "stop_lon": "-74.151399",
//         "stop_name": "Great Kills",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S19",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S19N",
//         "stop_lat": "40.551231",
//         "stop_lon": "-74.151399",
//         "stop_name": "Great Kills",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S19",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S19S",
//         "stop_lat": "40.551231",
//         "stop_lon": "-74.151399",
//         "stop_name": "Great Kills",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S20",
//         "stop_lat": "40.5564",
//         "stop_lon": "-74.136907",
//         "stop_name": "Bay Terrace",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S20",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S20N",
//         "stop_lat": "40.5564",
//         "stop_lon": "-74.136907",
//         "stop_name": "Bay Terrace",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S20",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S20S",
//         "stop_lat": "40.5564",
//         "stop_lon": "-74.136907",
//         "stop_name": "Bay Terrace",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S21",
//         "stop_lat": "40.56511",
//         "stop_lon": "-74.12632",
//         "stop_name": "Oakwood Heights",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S21",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S21N",
//         "stop_lat": "40.56511",
//         "stop_lon": "-74.12632",
//         "stop_name": "Oakwood Heights",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S21",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S21S",
//         "stop_lat": "40.56511",
//         "stop_lon": "-74.12632",
//         "stop_name": "Oakwood Heights",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S22",
//         "stop_lat": "40.57348",
//         "stop_lon": "-74.11721",
//         "stop_name": "New Dorp",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S22",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S22N",
//         "stop_lat": "40.57348",
//         "stop_lon": "-74.11721",
//         "stop_name": "New Dorp",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S22",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S22S",
//         "stop_lat": "40.57348",
//         "stop_lon": "-74.11721",
//         "stop_name": "New Dorp",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S23",
//         "stop_lat": "40.578965",
//         "stop_lon": "-74.109704",
//         "stop_name": "Grant City",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S23",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S23N",
//         "stop_lat": "40.578965",
//         "stop_lon": "-74.109704",
//         "stop_name": "Grant City",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S23",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S23S",
//         "stop_lat": "40.578965",
//         "stop_lon": "-74.109704",
//         "stop_name": "Grant City",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S24",
//         "stop_lat": "40.583591",
//         "stop_lon": "-74.103338",
//         "stop_name": "Jefferson Av",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S24",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S24N",
//         "stop_lat": "40.583591",
//         "stop_lon": "-74.103338",
//         "stop_name": "Jefferson Av",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S24",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S24S",
//         "stop_lat": "40.583591",
//         "stop_lon": "-74.103338",
//         "stop_name": "Jefferson Av",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S25",
//         "stop_lat": "40.588849",
//         "stop_lon": "-74.09609",
//         "stop_name": "Dongan Hills",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S25",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S25N",
//         "stop_lat": "40.588849",
//         "stop_lon": "-74.09609",
//         "stop_name": "Dongan Hills",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S25",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S25S",
//         "stop_lat": "40.588849",
//         "stop_lon": "-74.09609",
//         "stop_name": "Dongan Hills",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S26",
//         "stop_lat": "40.596612",
//         "stop_lon": "-74.087368",
//         "stop_name": "Old Town",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S26",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S26N",
//         "stop_lat": "40.596612",
//         "stop_lon": "-74.087368",
//         "stop_name": "Old Town",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S26",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S26S",
//         "stop_lat": "40.596612",
//         "stop_lon": "-74.087368",
//         "stop_name": "Old Town",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S27",
//         "stop_lat": "40.603117",
//         "stop_lon": "-74.084087",
//         "stop_name": "Grasmere",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S27",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S27N",
//         "stop_lat": "40.603117",
//         "stop_lon": "-74.084087",
//         "stop_name": "Grasmere",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S27",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S27S",
//         "stop_lat": "40.603117",
//         "stop_lon": "-74.084087",
//         "stop_name": "Grasmere",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S28",
//         "stop_lat": "40.621319",
//         "stop_lon": "-74.071402",
//         "stop_name": "Clifton",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S28",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S28N",
//         "stop_lat": "40.621319",
//         "stop_lon": "-74.071402",
//         "stop_name": "Clifton",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S28",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S28S",
//         "stop_lat": "40.621319",
//         "stop_lon": "-74.071402",
//         "stop_name": "Clifton",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S29",
//         "stop_lat": "40.627915",
//         "stop_lon": "-74.075162",
//         "stop_name": "Stapleton",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S29",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S29N",
//         "stop_lat": "40.627915",
//         "stop_lon": "-74.075162",
//         "stop_name": "Stapleton",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S29",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S29S",
//         "stop_lat": "40.627915",
//         "stop_lon": "-74.075162",
//         "stop_name": "Stapleton",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S30",
//         "stop_lat": "40.636949",
//         "stop_lon": "-74.074835",
//         "stop_name": "Tompkinsville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S30",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S30N",
//         "stop_lat": "40.636949",
//         "stop_lon": "-74.074835",
//         "stop_name": "Tompkinsville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S30",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S30S",
//         "stop_lat": "40.636949",
//         "stop_lon": "-74.074835",
//         "stop_name": "Tompkinsville",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "1",
//         "parent_station": "",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S31",
//         "stop_lat": "40.643748",
//         "stop_lon": "-74.073643",
//         "stop_name": "St George",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S31",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S31N",
//         "stop_lat": "40.643748",
//         "stop_lon": "-74.073643",
//         "stop_name": "St George",
//         "stop_url": "",
//         "zone_id": "",
//     },
//     {
//         "location_type": "0",
//         "parent_station": "S31",
//         "stop_code": "",
//         "stop_desc": "",
//         "stop_id": "S31S",
//         "stop_lat": "40.643748",
//         "stop_lon": "-74.073643",
//         "stop_name": "St George",
//         "stop_url": "",
//         "zone_id": "",
//     },
// ]


